title: Hello World
author: AleksejsSkripko
email: skripko.alexey@gmail.com
description: >Welcome
# social links
twitter_username: Aleksejs Skripko
github_username:  AleksejsSkripko

show_excerpts: true # set to false to remove excerpts on the homepage
